# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-rockpi"
github_repo = "siderolabs/sbc-rockpi"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
